#include <iostream>
using namespace std;

//CLASSES ARE NOT LIKE FUNCTIONS NEITHER THEIR SYNTAX 

// BY DEFAULT EVERY CLASS IS PRIVATE

class Student{ //UPPERCASE FIRST LETTER IS A COMMON PRACTICE 
public:


};// SEMICOLON IS IMP

int main(){

}