#include <iostream>
using namespace std;

//sign '~'

//THIS OPERATOR IS VERY TRICKY ~0 !=1 IT IS ~0=-1

//STEP 1 : CONVERT INTO BINARY UPTO 8 BITS AND TAKE COMPLEMENT 

//STEP 2 : THE FIRST DIGIT FROM THE LEFT TELLS US THE SIGN SO 1 = -ve and 0 = +ve

//STEP 3 : AGAIN TAKE THE COMPLEMENT OF THE REMAINING BITS(EXCLUDING MSB (MOST SIGNIFICANT BIT i.e THE FIRST BIT FROM LEFT))

//STEP 4 : ADD 1 AND AGAIN CONVERT TO DECIMAL

int main(){
    cout<<~0<<endl;

}